version: '3'
services:
  rabbitmq:
    image: rabbitmq:3.9.5-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  nestjs:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      RABBITMQ_QUEUE_NAME: email_notifications