version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  nodemailer:
    build:
      context: .
      dockerfile: Dockerfile.nodemailer
    environment:
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    depends_on:
      - mailhog
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE_NAME=my_queue
      - MAIL_SERVICE=nodemailer
    depends_on:
      - rabbitmq
      - nodemailer
  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
